<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

require_once 'modules/WEBH_HOOKS_REQUEST/SenderRequest.php';

class WEBH_HOOKS_REQUEST extends Basic
{
    public $new_schema = true;
    public $module_dir = 'WEBH_HOOKS_REQUEST';
    public $object_name = 'WEBH_HOOKS_REQUEST';
    public $table_name = 'webh_hooks_request';
    public $importable = false;
    public static $FINALE_STATUS = 'success';
    public static $ERROR_STATUS = 'error';
    public static $SEND_STATUS = 'ready_to_send';

    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $SecurityGroups;
    public $url;
    public $status;
    public $data;
    public $error_text;
    public $request_type;

    public function bean_implements($interface)
    {
        switch($interface)
        {
            case 'ACL':
                return true;
        }

        return false;
    }

    public function save($check_notify = false)
    {
        $data = $this->getArrayDataFromFields();
        $this->data = base64_encode(json_encode($data));
        parent::save($check_notify); // TODO: Change the autogenerated stub
        if($this->status == self::$SEND_STATUS){
            $this->send_request();
        }
        return $this->id;
    }

    public function retrieve($id = -1, $encode = true, $deleted = true)
    {
        parent::retrieve($id, $encode, $deleted); // TODO: Change the autogenerated stub
        $data = json_decode(base64_decode($this->data),1);
        if(!empty($data) && is_array($data)) {
            $i = 1;
            $iterator = "";
            foreach ($data as $k => $v) {
                $iterator = $this->get_field_number($i);
                $key_field_name = "key{$iterator}";
                $value_field_name = "value{$iterator}";
                $this->$key_field_name = $k;
                $this->$value_field_name = $v;
                $i++;
            }
        }
        return $this;
    }

    public function get_field_number(int $i):string {
        $iterator='';
        if ($i<10){
            $iterator = "0{$i}";
        } else {
            $iterator = "{$i}";
        }
        return $iterator;
    }

    public function send_request(){
        $data = $this->getArrayDataFromFields();
        $sendRequest = new SenderRequest($this->url,$data,$this->request_type);
        $result = $sendRequest->sendRequest();
        $this->saveResultRequerys($result);
    }

    public function getArrayDataFromFields() : array {
        $data=[];
        for($i=1; $i<=100;$i++){
            $iterator=$this->get_field_number($i);
            $key_field_name = "key{$iterator}";
            $value_field_name = "value{$iterator}";
            if (!empty($this->$key_field_name)){
                $data[$this->$key_field_name] = $this->$value_field_name;
            }
        }
        return $data;
    }

    public function saveResultRequerys(array $result){
        if($result['status'] == 'ok'){
            $this->saveSuccessResult($result['result']);
        } else {
            $this->saveErrorStatus($result['result']);
        }
    }

    public function saveSuccessResult($result){
        $this->description = $result;
        $this->status = self::$FINALE_STATUS;
        $this->save();
    }

    public function saveErrorStatus($result){
        $this->error_text = $result;
        $this->status = self::$ERROR_STATUS;
        $this->save();
        throw new Exception($result, 1);
    }
}